
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        uses: ./
        id: test
        env:
          master: prod
          staging: stg
        with:
          string: 'Env-{master}-{staging}'
      - name: Check equality
        run: 'echo ${{ steps.test.outputs.replaced }}'
